{
 "title": "Manage - Personal Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cw_db_name",
    "label": "Database Name i.e. cwwebapp_yourmsp",
    "query": "${VAR_CW_DB_NAME}"
   },
   {
    "name": "cw_company_id",
    "label": "Your MSP's company ID as it is in ConnectWise Manage",
    "query": "${VAR_CW_COMPANY_ID}"
   },
   {
    "name": "cw_api_url",
    "label": "i.e. https://api-au.myconnectwise.net/v4_6_release",
    "query": "${VAR_CW_API_URL}"
   },
   {
    "name": "cw_user",
    "label": "User:",
    "query": "SELECT [Member_ID] FROM [cwwebapp_yourmsp].[dbo].[v_ActiveMemberList]\nWHERE [Member_ID] NOT LIKE '%admin%'\nAND [Last_Name] IS NOT NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "Open Support Tickets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 0\n  AND [Board_Name] LIKE 'Support'\n  AND [parentTicketId] IS NULL\n  AND [ResourceList] LIKE '%$cw_user%'\n"
    }
   ]
  },
  {
   "title": "Open Tickets",
   "type": "table",
   "gridPos": { "h": 16, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n\t\t[SR_Service_RecID]\n      ,[Summary]\n      ,[Board_Name]\n      ,[Status_Name]\n      ,[Company_ID]\n      ,[Closed_Flag]\n      ,[SR_Type_Name]\n      ,[SR_SubType_Name]\n      ,[SR_SubTypeItem_Name]\n      ,[SR_Urgency_Name]\n      ,[Hours_Actual]\n      ,CAST(DATEDIFF(hh, [Date_Entered_UTC], GETUTCDATE())/24.0 as DECIMAL(10, 1)) as 'Age'\n      ,[Date_Resolved_UTC]\n      ,[Date_Resplan_UTC]\n      ,[Date_Responded_UTC]\n      ,[Resolved_Minutes]\n      ,[Resplan_Minutes]\n      ,[Responded_Minutes]\n      ,[IsInSla]\n      ,[Last_Update_UTC]\n      ,[ResourceList]\n      ,[Company_Name]\n      ,[Closed_By]\n      ,[SLA_Name]\n      ,[parentTicketId]\n      ,SUBSTRING([SR_Urgency_Name], 10,1) AS 'Urgency'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 0\n  AND [parentTicketId] IS NULL\n  AND [ResourceList] LIKE '%$cw_user%'\n  AND [Board_Name] NOT LIKE 'Documentation'\n  ORDER BY SR_Urgency_Name, Age DESC\n"
    }
   ]
  },
  {
   "title": "Open Alert Tickets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 0\n  AND [Board_Name] LIKE 'Alerts'\n  AND [parentTicketId] IS NULL\n  AND [ResourceList] LIKE '%$cw_user%'\n"
    }
   ]
  },
  {
   "title": "Tickets Opened vs Closed (Last 30 Days)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup([Date_Entered_UTC], '1d',0) as time, ISNULL(count([SR_Service_RecID]), 0) as 'Opened Tickets'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE ([Board_Name] LIKE 'Support' OR [Board_Name] LIKE 'Triage')\n  AND [parentTicketId] IS NULL\n  AND [Entered_By] LIKE '$cw_user'\n  AND [Date_Entered_UTC] > GETUTCDATE() - 30\n  GROUP BY $__timeGroup([Date_Entered_UTC], '1d',0)\n  ORDER BY $__timeGroup([Date_Entered_UTC], '1d',0)"
    },
    {
     "rawSql": "SELECT $__timeGroup([Date_Closed_UTC], '1d',0) as time, ISNULL(count([SR_Service_RecID]), 0) as 'Closed Tickets'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE ([Board_Name] LIKE 'Support' OR [Board_Name] LIKE 'Triage')\n  AND [parentTicketId] IS NULL\n  AND [Closed_By] LIKE '$cw_user'\n  AND [Date_Closed_UTC] > GETUTCDATE() - 30\n  GROUP BY $__timeGroup([Date_Closed_UTC], '1d',0)\n  ORDER BY $__timeGroup([Date_Closed_UTC], '1d',0)"
    }
   ]
  },
  {
   "title": "Closed Tickets in the Last 12hrs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n      [Closed_By], \n      COUNT(*) as 'Closed last 24 hrs'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 1\n  AND ([Board_Name] LIKE 'Support' OR [Board_Name] LIKE 'Alerts')\n  AND [parentTicketId] IS NULL\n  AND [Date_Closed_UTC] > GETUTCDATE() - 0.5\n  AND [Hours_Actual] > 0\n  AND [Closed_By] NOT LIKE 'Automate'\n  GROUP BY [Closed_By]\n  ORDER BY 'Closed last 24 hrs' DESC"
    }
   ]
  },
  {
   "title": "Ticket Statuses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n      [Status_Name], \n      COUNT(*) as 'Status'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [parentTicketId] IS NULL\n  AND [Status_Name] NOT LIKE '>%'\n  AND [ResourceList] LIKE '%$cw_user%'\n  AND [Board_Name] NOT LIKE 'Documentation'\n  GROUP BY [Status_Name]\n  ORDER BY 'Status' DESC"
    }
   ]
  }
 ]
}