{
 "title": "Manage Test",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cw_api_url",
    "label": "i.e. https://api-au.myconnectwise.net/v4_6_release",
    "query": "${VAR_CW_API_URL}"
   },
   {
    "name": "cw_company_id",
    "label": "Your MSP's company ID as it is in ConnectWise Manage",
    "query": "${VAR_CW_COMPANY_ID}"
   },
   {
    "name": "cw_db_name",
    "label": "Database Name i.e. cwwebapp_yourmsp",
    "query": "${VAR_CW_DB_NAME}"
   }
  ]
 },
 "panels": [
  {
   "title": "Test Open Support Tickets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 0\n  AND [Board_Name] LIKE 'Support'\n  AND [parentTicketId] IS NULL\n"
    }
   ]
  },
  {
   "title": "Unassigned Tickets (TODO - Age)",
   "type": "table",
   "gridPos": { "h": 15, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n\t\t[SR_Service_RecID]\n      ,[Summary]\n      ,[Board_Name]\n      ,[Status_Name]\n      ,[Company_ID]\n      ,[Closed_Flag]\n      ,[SR_Type_Name]\n      ,[SR_SubType_Name]\n      ,[SR_SubTypeItem_Name]\n      ,[SR_Urgency_Name]\n      ,[Hours_Actual]\n      ,[Date_Resolved_UTC]\n      ,[Date_Resplan_UTC]\n      ,[Date_Responded_UTC]\n      ,[Resolved_Minutes]\n      ,[Resplan_Minutes]\n      ,[Responded_Minutes]\n      ,[IsInSla]\n      ,[Last_Update_UTC]\n      ,[ResourceList]\n      ,[Company_Name]\n      ,[Closed_By]\n      ,[SLA_Name]\n      ,[parentTicketId]\n      ,SUBSTRING([SR_Urgency_Name], 10,1) AS 'Urgency'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 0\n  AND [Board_Name] LIKE 'Support'\n  AND [parentTicketId] IS NULL\n  AND ResourceList IS NULL\n  ORDER BY SR_Urgency_Name, SR_Service_RecID DESC\n"
    }
   ]
  },
  {
   "title": "Closed Tickets in the Last 24 hrs (Time > 0)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n      [Closed_By], \n      COUNT(*) as 'Closed last 24 hrs'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 1\n  AND [Board_Name] LIKE 'Support'\n  AND [parentTicketId] IS NULL\n  AND [Date_Closed_UTC] > GETUTCDATE() -1\n  AND [Hours_Actual] > 0\n  GROUP BY [Closed_By]\n  ORDER BY 'Closed last 24 hrs' DESC"
    }
   ]
  },
  {
   "title": "Closed Tickets in the Last 24 hrs (Time > 0)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n      [Closed_By], \n      COUNT(*) as 'Closed last 24 hrs'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 1\n  AND [Board_Name] LIKE 'Support'\n  AND [parentTicketId] IS NULL\n  AND [Date_Closed_UTC] > GETUTCDATE() -1\n  AND [Hours_Actual] > 0\n  GROUP BY [Closed_By]\n  ORDER BY 'Closed last 24 hrs' DESC"
    }
   ]
  }
 ]
}