{
 "title": "Manage - Help Desk",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "cw_api_url",
    "label": "i.e. https://api-au.myconnectwise.net/v4_6_release",
    "query": "${VAR_CW_API_URL}"
   },
   {
    "name": "cw_company_id",
    "label": "Your MSP's company ID as it is in ConnectWise Manage",
    "query": "${VAR_CW_COMPANY_ID}"
   },
   {
    "name": "cw_db_name",
    "label": "Database Name i.e. cwwebapp_yourmsp",
    "query": "${VAR_CW_DB_NAME}"
   },
   {
    "name": "random_delay",
    "label": "Random delay, between zero and $random_delay seconds",
    "query": "${VAR_RANDOM_DELAY}"
   }
  ]
 },
 "panels": [
  {
   "title": "Open Support Tickets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT count(*)\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 0\n  AND [Board_Name] LIKE 'Support'\n  AND [parentTicketId] IS NULL\n"
    }
   ]
  },
  {
   "title": "Tickets Opened Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT COUNT(*)\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 1\n  AND ([Board_Name] LIKE 'Support' OR [Board_Name] LIKE 'Triage')\n  AND [parentTicketId] IS NULL\n  AND [Date_Closed_UTC] > GETUTCDATE() - 0.5"
    }
   ]
  },
  {
   "title": "Unassigned Tickets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT COUNT(*)\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 0\n  AND [Board_Name] LIKE 'Triage'\n  AND [parentTicketId] IS NULL"
    }
   ]
  },
  {
   "title": "Unassigned Tickets on Support Board",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT COUNT(*)\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 0\n  AND [Board_Name] LIKE 'Support'\n  AND [parentTicketId] IS NULL\n  AND ResourceList IS NULL"
    }
   ]
  },
  {
   "title": "Breached ResPlan",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT COUNT(*)\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 0\n  AND [Board_Name] LIKE 'Support'\n  AND [parentTicketId] IS NULL\n  AND [SR_Urgency_Name] LIKE 'Priority 0 - MSP'\n  AND [IsInSLA] = 0\n"
    }
   ]
  },
  {
   "title": "Tickets not updated in 3 days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT count(*)\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 0\n  AND ([Board_Name] LIKE 'Support' OR [Board_Name] LIKE 'Triage')\n  AND [parentTicketId] IS NULL\n  AND [Last_Update_UTC] < GETUTCDATE() - 3\n  AND [Status_Name] NOT LIKE 'Awaiting Hardware'\n  AND [Status_Name] NOT LIKE 'Awaiting Onsite'\n  AND [Status_Name] NOT LIKE 'Scheduled'\n"
    }
   ]
  },
  {
   "title": "Tickets Closed Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT COUNT(*)\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 1\n  AND ([Board_Name] LIKE 'Support')\n  AND [parentTicketId] IS NULL\n  AND [Date_Entered_UTC] > GETUTCDATE() - 0.5"
    }
   ]
  },
  {
   "title": "Closed Tickets in the Last 12hrs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT\n      [Closed_By], \n      COUNT(*) as 'Closed last 24 hrs'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE [Closed_Flag] = 1\n  AND ([Board_Name] LIKE 'Support' OR [Board_Name] LIKE 'Alerts')\n  AND [parentTicketId] IS NULL\n  AND [Date_Closed_UTC] > GETUTCDATE() - 0.5\n  AND [Hours_Actual] > 0\n  GROUP BY [Closed_By]\n  ORDER BY 'Closed last 24 hrs' DESC"
    }
   ]
  },
  {
   "title": "Hours Logged Today",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT Member_Name, SUM([Hours_Actual]) as 'Sum_Hours_Actual'\n  FROM [$cw_db_name].[dbo].[v_api_collection_time_entry]\n  WHERE [Time_Start] > GETUTCDATE() - 0.5\n  AND [Time_End] < GETUTCDATE() + 0.5\n  GROUP BY [Member_Name]\n  ORDER BY 'Sum_Hours_Actual' DESC"
    }
   ]
  },
  {
   "title": "Tickets Opened vs Closed (Last 14 Days)",
   "type": "graph",
   "description": "Excludes Automate Tickets",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT CAST([Date_Entered_UTC] as DATE) as time, ISNULL(count([SR_Service_RecID]), 0) as 'Opened Tickets'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE ([Board_Name] LIKE 'Support' OR [Board_Name] LIKE 'Triage')\n  AND [parentTicketId] IS NULL\n  AND [Entered_By] NOT LIKE 'Automate'\n  AND [Date_Entered_UTC] > GETUTCDATE() - 14\n  GROUP BY CAST([Date_Entered_UTC] as DATE)\n  ORDER BY time"
    },
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT $__timeGroup([Date_Closed_UTC], '1d',0) as time, ISNULL(count([SR_Service_RecID]), 0) as 'Closed Tickets'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE ([Board_Name] LIKE 'Support' OR [Board_Name] LIKE 'Triage')\n  AND [parentTicketId] IS NULL\n  AND [Closed_By] NOT LIKE 'Automate'\n  AND [Date_Closed_UTC] > GETUTCDATE() - 14\n  GROUP BY $__timeGroup([Date_Closed_UTC], '1d',0)\n  ORDER BY $__timeGroup([Date_Closed_UTC], '1d',0)"
    }
   ]
  },
  {
   "title": "Hours logged this week",
   "type": "bargauge",
   "description": "Hours logged on this week's timesheet",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT [Member_Name],\n        [TS_Hours]\n  FROM [$cw_db_name].[dbo].[v_api_collection_time_sheet]\n  WHERE [Date_End] < GETDATE() + 7\n  AND [Date_Start] > GETDATE() - 7\n  ORDER BY [TS_Hours] DESC"
    }
   ]
  },
  {
   "title": "Ticket categories, last 7 days (NEEDS FIXING?)",
   "type": "bargauge",
   "description": "Excludes Automate-closed tickets",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "DECLARE @RandomDelay int = ABS(CHECKSUM(NEWID()) % ($random_delay-1))\nWAITFOR DELAY @RandomDelay\nSELECT\n      [SR_Type_Name], \n      COUNT(*) as 'Ticket Types last 7 days'\n  FROM [$cw_db_name].[dbo].[v_api_collection_service_ticket]\n  WHERE ([Board_Name] LIKE 'Support')\n  AND [parentTicketId] IS NULL\n  AND [Date_Entered_UTC] > GETUTCDATE() - 7\n  AND [Closed_By] NOT LIKE 'Automate'\n  GROUP BY [SR_Type_Name]\n  ORDER BY 'Ticket Types last 7 days' DESC"
    }
   ]
  }
 ]
}